trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: vcpkg install riffcpp
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
- job: Windows_x64_static
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    VCPKG_DEFAULT_TRIPLET: x64-windows-static
  steps:
  - script: vcpkg install riffcpp
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=OFF -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
- job: Windows_x64
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    VCPKG_DEFAULT_TRIPLET: x64-windows
  steps:
  - script: vcpkg install riffcpp
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=OFF -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
