jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: git clone --depth=1 https://github.com/libdmusic/vcpkg
  - script: ./vcpkg/bootstrap-vcpkg.sh
  - script: ./vcpkg/vcpkg install riffcpp
  - script: |
      mkdir build
      cd build
      cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
- job: Windows_x64_static
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: git clone --depth=1 https://github.com/libdmusic/vcpkg
  - script: .\vcpkg\bootstrap-vcpkg.bat
  - script: .\vcpkg\vcpkg.exe install riffcpp:x64-windows-static
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
- job: Windows_x64
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: git clone --depth=1 https://github.com/libdmusic/vcpkg
  - script: .\vcpkg\bootstrap-vcpkg.bat
  - script: .\vcpkg\vcpkg.exe install riffcpp:x64-windows
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=ON -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
      cmake --build .
