name: Build

on: [push]

jobs:
  build-ubuntu:
    name: Ubuntu build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shared: ['ON', 'OFF']
        buildtype: ['Debug', 'Release']
        simd: ['OFF', 'SSE3']
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: mkdir build
    - name: Install dependencies
      run: |
           sudo add-apt-repository ppa:libdmusic/unstable
           sudo apt-get update
           sudo apt-get install libriffcpp-dev
    - name: Configure
      working-directory: build
      run: cmake ${GITHUB_WORKSPACE} -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_BUILD_TYPE=${{ matrix.buildtype }} -DDLSYNTH_ENABLE_SIMD=${{ matrix.simd }}
    - name: Build
      working-directory: build
      run: cmake --build .
  
  build-windows:
    name: Windows build
    runs-on: windows-latest
    strategy:
      matrix:
        buildtype: ['Debug', 'Release']
        simd: ['OFF', 'SSE3']
        shared: ['ON', 'OFF']
        plat: ['Win32', 'x64']
        include:
          - shared: 'ON'
            plat: 'Win32'
            triplet: 'x86-windows'
          - shared: 'OFF'
            plat: 'Win32'
            triplet: 'x86-windows-static'
          - shared: 'ON'
            plat: 'x64'
            triplet: 'x64-windows'
          - shared: 'OFF'
            plat: 'x64'
            triplet: 'x64-windows-static'
    
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: mkdir build
    - name: Download vcpkg
      run: git clone --depth=1 https://github.com/Microsoft/vcpkg
    - name: Build vcpkg
      working-directory: vcpkg
      run: |
           .\scripts\bootstrap.ps1
           .\vcpkg.exe install --triplet ${{ matrix.triplet }} riffcpp
    - name: Configure
      working-directory: build
      run: cmake $env:GITHUB_WORKSPACE -A ${{ matrix.plat }} -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DVCPKG_TARGET_TRIPLET=${{ matrix.triplet }} -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DDLSYNTH_ENABLE_SIMD=${{ matrix.simd }}
    - name: Build
      working-directory: build
      run: cmake --build . --config ${{ matrix.buildtype }}
