name: Build & deploy docs

on: [push]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Generate docs
      run: doxygen
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: docs

  update-pages:
    name: Upload docs to GH Pages
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/gh-pages
    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: docs
        path: .
    - name: Test
      run: git status