name: Build & deploy docs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Generate docs
      run: doxygen
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs