name: Build & deploy docs

on: [push]

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Generate docs
      run: doxygen
    - name: Upload artifact
      uses: actions/upload-artifact@master
      name: docs
      path: docs