name: Build & deploy docs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Generate docs
      run: doxygen
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: docs
        path: docs

  update-pages:
    name: Upload docs to GH Pages
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/gh-pages
    - name: Download artifact
      uses: actions/download-artifact@master
      with:
        name: docs
        path: .
    - name: Commit changes
      run: |
        git config --local user.email "francesco@bertolaccini.dev"
        git config --local user.name "Francesco Bertolaccini"
        git commit -m "Update docs" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages