name: Build

on: [push]

jobs:
  build-ubuntu:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/gh-pages
        path: docs
    - name: Install Doxygen
      run: sudo apt-get install doxygen
    - name: Generate docs
      run: doxygen